/*
 * generated by Xtext 2.24.0
 */
package org.xtext.example.mydsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BookingDSLStandaloneSetup extends BookingDSLStandaloneSetupGenerated {

	public static void doSetup() {
		new BookingDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
